<a href="https://colab.research.google.com/github/Adrizg11/Inteligencia-Artificial/blob/main/Lecci%C3%B3nNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
# Create a 1D array of numbers from 0 to 9
# your code here
import numpy as np

pass

In [26]:
# Create random vector of size 10 and replace the maximum value by 0lista=list(range(9))
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0

print("Original random vector:", random_vector)


Original random vector: [0.62994503 0.4485295  0.26359272 0.         0.84680684 0.00935069
 0.81820842 0.88218659 0.79120107 0.20971665]


In [27]:
vector = np.random.rand(10)
vector[vector.argmax()] = 0
print(vector)

pass

[0.83029321 0.         0.01347913 0.29139425 0.52668096 0.32489949
 0.01121362 0.45290155 0.40871181 0.14648902]


In [28]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

pass

8


In [29]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])
pass

[3 4 5]


In [30]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:])
pass

[4 5 6 7]


In [31]:
# Create a 3×3 numpy array of all True’s
tmp=10*np.random.random((4,4))
mascara=tmp>0
print(tmp)
print("-------------------")
print(mascara)
pass

[[1.9637841  1.2080923  5.00124388 0.32074698]
 [2.78552239 2.18499009 4.11612571 4.74482509]
 [2.54111149 1.19526299 1.45062556 5.14477024]
 [8.53555213 5.04913552 4.83865599 7.85520509]]
-------------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [32]:
# Extract all odd numbers from arr
tmp = np.random.randint(1, 11, size=(4, 4))
print(tmp)

print('----------------------------------')

mask = np.mod(tmp, 2) == 0
print(tmp[mask])
pass


[[ 7  4  4  3]
 [ 2  5  3  3]
 [ 4  4 10  8]
 [ 4  3  4  1]]
----------------------------------
[ 4  4  2  4  4 10  8  4  4]


In [33]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
tmp = np.arange(10,50)
print(tmp)
pass

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [34]:
# Reverse a vector (first element becomes last)
vectorInvertido = tmp[::-1]
print(vectorInvertido)
pass

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [35]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
tmp = np.random.randint(1, 101, size=(10, 10))
minimo = np.min(tmp)
maximo = np.max(tmp)
print("Matriz")
print(tmp)
print("Minimo")
print(minimo)
print("Maximo")
print(maximo)
pass

Matriz
[[ 72  78  94  82  46   1   5  45  47  83]
 [ 41  15  39  88  12  80  10  82  69  73]
 [ 48  28  26  57   1  35  10  19  58   1]
 [ 39  84  69  16  66  26  52  11  75  75]
 [ 20  66  81  59   3  77   5  28  13 100]
 [ 63  22  22  19  53  44  58  13  41  73]
 [ 62  77   5   8  62   8  45  52   7   6]
 [ 38  47  58  64   8  55  14  54  40  99]
 [ 77  26  58  96  84 100  81  62  35  84]
 [ 91  72  82  82  56  96  70  68  42  38]]
Minimo
1
Maximo
100


In [36]:
# Create a 3x3x3 array with random values
tmp2 = np.random.random((3,3,3))
print(tmp2)
pass

[[[0.64608739 0.79873653 0.65357056]
  [0.17349187 0.11827381 0.25154367]
  [0.13343363 0.14740118 0.4495404 ]]

 [[0.27422975 0.13749434 0.88813096]
  [0.34560967 0.05869343 0.31164085]
  [0.06408743 0.2565369  0.39784725]]

 [[0.68309544 0.86151455 0.96475917]
  [0.66177935 0.19123698 0.8735089 ]
  [0.25658535 0.36365568 0.26414166]]]


In [37]:
# Replace all odd numbers in arr with -1
tmp = np.random.randint(1, 11, size=(3, 3, 3))
print(tmp)
print("-----------------")
tmp[tmp % 2 == 1] = -1
print(tmp)
pass

[[[ 8  1  5]
  [10  9  4]
  [ 9  7  3]]

 [[ 1  7  1]
  [ 7  5  9]
  [ 2  1  6]]

 [[ 1  6  7]
  [ 5  5  9]
  [ 3  5 10]]]
-----------------
[[[ 8 -1 -1]
  [10 -1  4]
  [-1 -1 -1]]

 [[-1 -1 -1]
  [-1 -1 -1]
  [ 2 -1  6]]

 [[-1  6 -1]
  [-1 -1 -1]
  [-1 -1 10]]]


In [38]:
# Create an array of type float
tmpF = np.random.rand(5)
print(tmpF)
pass

[0.05984251 0.45846832 0.58821857 0.55003675 0.95110071]


In [39]:
# Convert a 1D array to a 2D array with 2 rows
lista = list(range(12))
lista = np.array(lista)
two_d_array = lista.reshape(2, 6)
print(two_d_array)

pass


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [40]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
valoresComunes = np.intersect1d(Z1, Z2)
print(Z1)
print("-------------")
print(Z2)
print("-------------")
print(valoresComunes)
pass


[8 7 5 7 9 6 3 0 2 8]
-------------
[0 7 8 6 2 3 5 0 8 8]
-------------
[0 2 3 5 6 7 8]


In [41]:
#  Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print('Array A')
print(A)
print('Array B')
print(B)

if np.array_equal(A,B):
  print('Son iguales')
else:
  print('Son diferentes')

pass

Array A
[1 1 1 0 1]
Array B
[0 0 0 0 1]
Son diferentes


In [42]:
# Stack arrays a and b vertically
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaVertical = np.vstack((A, B))
print("Stacked Array:")
print(matrizApiladaVertical)
pass

Array A
[1 1 1 0 1]
Array B
[0 0 0 0 1]
Stacked Array:
[[1 1 1 0 1]
 [0 0 0 0 1]]


In [43]:
# Stack the arrays a and b horizontally.
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaHorizontal = np.hstack((A, B))
print("Stacked Array:")
print(matrizApiladaHorizontal)
pass

Array A
[1 1 1 0 1]
Array B
[0 0 0 0 1]
Stacked Array:
[1 1 1 0 1 0 0 0 0 1]


In [44]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
print(tmp)
print('-------------')
valores = tmp[(tmp>=5)&(tmp<=10)]
print(valores)
# pass

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-------------
[ 5  6  7  8  9 10]


In [45]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


"""Arrays"""
# a = np.array([5, 7, 9, 8, 6, 4, 5])
a = np.random.randint(1,10,7)
print("Array A")
print(a)
# b = np.array([6, 3, 4, 8, 9, 7, 1])
b = np.random.randint(1,10,7)
print("Array B")
print(b)

print("----------------------------")

"""Method 1"""
print("Method 1")
def parMax(a, b):
    """Get the element-wise maximum of two arrays"""
    return np.maximum(a, b)

c = parMax(a, b)
print(c)

print("----------------------------")

print("Method 2")
"""Method 2"""
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

c = np.array([maxx(x, y) for x, y in zip(a, b)])
print(c)

Array A
[3 4 1 6 4 4 8]
Array B
[2 2 5 6 6 3 4]
----------------------------
Method 1
[3 4 5 6 6 4 8]
----------------------------
Method 2
[3 4 5 6 6 4 8]


In [46]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print("------------------------")
print("Cambio de columnas 1 y 2")
print(arr)

pass

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------
Cambio de columnas 1 y 2
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [47]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)


[[8.93055899 8.26653862 9.337262  ]
 [5.52993547 8.89700523 9.40824948]
 [7.31543943 8.03123008 7.29093248]
 [6.36894462 6.74569651 8.84341324]
 [7.82327348 7.77754215 7.725359  ]]
