<a href="https://colab.research.google.com/github/Adrizg11/Inteligencia-Artificial/blob/main/Nunpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.random.randint(1,11,size=(3,4))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)
print('multiply numbers')
print(a*b)

print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[2 4 8 9]
 [2 9 1 2]
 [5 2 6 1]]
[[10 10  5  4]
 [ 7 10  9  9]
 [ 4  4  5  3]]
(3, 4)
(3, 4)
adding numbers
[[12 14 13 13]
 [ 9 19 10 11]
 [ 9  6 11  4]]
substracting numbers
[[-8 -6  3  5]
 [-5 -1 -8 -7]
 [ 1 -2  1 -2]]
multiply numbers
[[20 40 40 36]
 [14 90  9 18]
 [20  8 30  3]]
[[12 14 13 13]
 [ 9 19 10 11]
 [ 9  6 11  4]]
[[20 40 40 36]
 [14 90  9 18]
 [20  8 30  3]]
[[0.2        0.4        1.6        2.25      ]
 [0.28571429 0.9        0.11111111 0.22222222]
 [1.25       0.5        1.2        0.33333333]]


In [3]:
a=np.random.randint(1,11,size=(2,3))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[ 4  7  6]
 [10  2  5]]
[[ 2  1  4  7]
 [ 4  7  9 10]
 [ 6  4  7  3]]
[[ 72  77 121 116]
 [ 58  44  93 105]]
[[ 72  77 121 116]
 [ 58  44  93 105]]


In [4]:
a=np.random.randint(1,11,size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[ 2 10]
 [ 1  5]]
[[ 2  1]
 [10  5]]


In [6]:
a=np.random.randint(1,11,size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('------------------')
print(c)



(4, 3)
(3,)
[[10  8  1]
 [ 3  1  8]
 [ 5  5  1]
 [ 5 10  2]]
[1 0 2]
(4, 3)
------------------
[[10  4  8]
 [ 1  8 10]
 [ 8  6  9]
 [ 8  3  8]]


In [8]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)
print('------------------')
c=a+b
print(c)

[[10  8  1]
 [ 3  1  8]
 [ 5  5  1]
 [ 5 10  2]]
[1 0 2]
[[11  8  3]
 [ 4  1 10]
 [ 6  5  3]
 [ 6 10  4]]
------------------
[[11  8  3]
 [ 4  1 10]
 [ 6  5  3]
 [ 6 10  4]]


In [9]:
a=np.array([1,2,3])


#print(a)


tmp=np.tile(a,(6,1))
print(tmp)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [17]:
matriz = np.random.randint(0, 10, size=(6, 6))
print(matriz)

aux=np.mean(matriz)
print(aux)
print('------------------')
matriz = np.random.randint(0, 10, size=(6, 6))
print(matriz)
print('------------------')
promedio_por_filas = np.mean(matriz, axis=1)
print("\nEl promedio por filas de la matriz es:")
print(promedio_por_filas)

[[3 4 4 1 2 2]
 [9 1 3 6 8 3]
 [1 6 1 5 7 1]
 [6 3 5 8 1 5]
 [2 9 1 6 6 3]
 [2 7 6 2 5 9]]
4.25
------------------
[[1 9 1 3 2 8]
 [5 4 8 6 0 4]
 [6 6 0 5 8 1]
 [7 2 9 8 3 5]
 [5 2 6 0 7 8]
 [4 9 0 9 3 8]]
------------------

El promedio por filas de la matriz es:
[4.         4.5        4.33333333 5.66666667 4.66666667 5.5       ]


In [18]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)

arr = np.array([1, 2, 3])
squared_arr = np.square(arr)

In [19]:
print(squared_arr)

[1 4 9]


In [21]:
# Broadcasting con arrays de diferentes dimensiones
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result_broadcasting = arr_2d + arr_1d

print("Resultado del Broadcasting:")
print(result_broadcasting)

# Concatenación de arrays a lo largo de diferentes ejes
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6]])
concatenated_arr = np.concatenate((arr_a, arr_b.T), axis=1)

print("\nResultado de la Concatenación:")
print(concatenated_arr)

Resultado del Broadcasting:
[[11 22 33]
 [14 25 36]]

Resultado de la Concatenación:
[[1 2 5]
 [3 4 6]]
